//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniComMediaPlanner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int Id { get; set; }
        public string Ad_Title { get; set; }
        public int MediaChannel_Id { get; set; }
        public int Supplier_Id { get; set; }
        public decimal Budget { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public int Campaign_Id { get; set; }
    
        public virtual Ad Ad1 { get; set; }
        public virtual Ad Ad2 { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual MediaChannel MediaChannel { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
