//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniComMediaPlanner.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign_Supplier
    {
        public int Id { get; set; }
        public int Campaign_Id { get; set; }
        public int Supplier_Id { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
